services:
  dy_frontend:
    container_name: dy_frontend
    image: dy_frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    restart: always
    depends_on:
      - dy_backend
  dy_backend:
    container_name: dy_backend
    image: dy_backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@dy_database:5432/postgres?schema=public
  dy_database:
    container_name: dy_database
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5434:5434
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
